In [15]:
import csv
import pandas as pd

In [16]:
esg_df = pd.read_csv("ESG_csv.csv")

In [3]:
esg_df

,Country,EPI 2000,EPI 2002,EPI 2004,EPI 2006,EPI 2008,EPI 2010,EPI 2012,EPI 2014,EPI 2016,...,GDP PER CAPITA 2011,GDP PER CAPITA 2012,GDP PER CAPITA 2013,GDP PER CAPITA 2014,GDP PER CAPITA 2015,GDP PER CAPITA 2016,GDP PER CAPITA 2017,GDP PER CAPITA 2018,GDP PER CAPITA 2019,GDP PER CAPITA 2020
0,Albania,58.98,61.43,64.54,66.62,67.46,71.42,65.85,54.73,74.38,...,10207.73,10526.32,10570.97,11259.30,11658.87,12078.80,12770.98,13546.48,14230.99,13817.76
1,Algeria,46.81,47.51,48.17,48.93,49.79,67.41,48.56,50.08,70.28,...,13500.04,13303.33,13056.80,13003.27,12015.63,11624.34,11737.42,11921.73,11997.34,11268.26
2,Angola,42.79,43.72,45.15,47.51,48.47,36.35,47.57,28.69,51.32,...,6710.75,7412.97,7682.48,8179.30,7337.57,7103.23,7310.90,7099.97,6952.42,6538.45
3,Argentina,51.73,53.01,53.12,55.20,56.07,61.05,56.48,49.55,79.84,...,19322.23,19641.35,20131.68,19683.77,20105.20,20307.87,23597.12,23305.85,22996.99,20767.61
4,Armenia,44.61,46.23,46.64,46.65,46.46,60.44,47.48,61.67,81.60,...,8025.46,9364.38,9835.80,10036.89,9969.66,10704.23,12115.14,13020.40,14231.18,13284.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,Uruguay,56.27,59.40,57.67,57.00,56.80,59.11,57.06,53.61,73.98,...,18002.89,18192.33,19130.06,20093.62,20217.56,22454.39,23009.87,23588.15,24006.79,22795.06
120,Uzbekistan,29.12,29.39,30.53,31.40,32.17,42.27,32.24,43.23,63.67,...,5489.08,5712.82,5942.40,6158.50,6343.15,6452.93,6518.80,6917.68,7310.96,7378.25
121,Vietnam,48.39,49.85,48.88,49.87,50.63,59.00,50.64,38.17,58.50,...,4523.25,5042.48,5358.95,5745.21,6102.64,6572.98,7155.44,7768.08,8381.24,8650.65
122,Zambia,53.57,53.30,54.14,53.90,55.24,47.00,55.56,41.72,66.06,...,3323.94,3422.62,3578.85,3539.44,3430.40,3404.67,3485.02,3606.09,3617.21,3449.61
123,Zimbabwe,49.47,49.71,50.38,50.54,51.80,47.82,52.76,49.54,59.25,...,2101.82,2375.93,2560.77,2612.46,2679.51,2806.47,3274.61,3421.90,3155.70,2895.42

In [17]:
regional_df = pd.read_csv("cont_data.csv")
pop_df = pd.read_csv("pop_csv.csv")

In [18]:
pop_df.head(40)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54208,55434,56234,56699,57029,57357,...,102050,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765,134159786,137614644,141202036,144920186,148769974,...,532760424,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996967,9169406,9351442,9543200,9744772,9956318,...,30117411,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,96396419,98407221,100506960,102691339,104953470,107289875,...,360285439,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5454938,5531451,5608499,5679409,5734995,5770573,...,24220660,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0
5,Albania,ALB,"Population, total",SP.POP.TOTL,1608800,1659800,1711319,1762621,1814135,1864791,...,2905195,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,2837743.0
6,Andorra,AND,"Population, total",SP.POP.TOTL,13410,14378,15379,16407,17466,18542,...,83748,82427.0,80770.0,79213.0,77993.0,77295.0,76997.0,77008.0,77146.0,77265.0
7,Arab World,ARB,"Population, total",SP.POP.TOTL,92197715,94724540,97334438,100034191,102832792,105736428,...,363156846,371437642.0,379696477.0,387899835.0,396028301.0,404042892.0,411942825.0,419851989.0,427870273.0,436080728.0
8,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,92417,100801,112112,125130,138049,149855,...,8946778,9141598.0,9197908.0,9214182.0,9262896.0,9360975.0,9487206.0,9630966.0,9770526.0,9890400.0
9,Argentina,ARG,"Population, total",SP.POP.TOTL,20481781,20817270,21153042,21488916,21824427,22159644,...,41261490,41733271.0,42202935.0,42669500.0,43131966.0,43590368.0,44044811.0,44494502.0,44938712.0,45376763.0
10,Armenia,ARM,"Population, total",SP.POP.TOTL,1874119,1941498,2009524,2077584,2145004,2211316,...,2876536,2884239.0,2897593.0,2912403.0,2925559.0,2936147.0,2944789.0,2951741.0,2957728.0,2963234.0
11,American Samoa,ASM,"Population, total",SP.POP.TOTL,20127,20605,21246,22029,22850,23675,...,55755,55669.0,55717.0,55791.0,55806.0,55739.0,55617.0,55461.0,55312.0,55197.0
12,Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,54132,55005,55849,56701,57641,58699,...,89250,90407.0,91510.0,92562.0,93571.0,94520.0,95425.0,96282.0,97115.0,97928.0
13,Australia,AUS,"Population, total",SP.POP.TOTL,10276477,10483000,10742000,10950000,11167000,11388000,...,22340024,22733465.0,23128129.0,23475686.0,23815995.0,24190907.0,24601860.0,24982688.0,25365745.0,25687041.0
14,Austria,AUT,"Population, total",SP.POP.TOTL,7047539,7086299,7129864,7175811,7223801,7270889,...,8391643,8429991.0,8479823.0,8546356.0,8642699.0,8736668.0,8797566.0,8840521.0,8879920.0,8917205.0
15,Azerbaijan,AZE,"Population, total",SP.POP.TOTL,3895398,4030325,4171428,4315127,4456691,4592601,...,9173082,9295784.0,9416801.0,9535079.0,9649341.0,9757812.0,9854033.0,9939771.0,10024283.0,10110116.0
16,Burundi,BDI,"Population, total",SP.POP.TOTL,2797925,2852438,2907320,2964416,3026292,3094378,...,8958406,9245992.0,9540302.0,9844301.0,10160034.0,10488002.0,10827010.0,11175379.0,11530577.0,11890781.0
17,Belgium,BEL,"Population, total",SP.POP.TOTL,9153489,9183948,9220578,9289770,9378113,9463667,...,11038264,11106932.0,11159407.0,11209057.0,11274196.0,11331422.0,11375158.0,11427054.0,11488980.0,11555997.0
18,Benin,BEN,"Population, total",SP.POP.TOTL,2431617,2465865,2502897,2542864,2585961,2632361,...,9460829,9729254.0,10004594.0,10286839.0,10575962.0,10872072.0,11175192.0,11485035.0,11801151.0,12123198.0
19,Burkina Faso,BFA,"Population, total",SP.POP.TOTL,4829289,4894580,4960328,5027811,5098891,5174874,...,16081915,16571252.0,17072791.0,17586029.0,18110616.0,18646350.0,19193236.0,19751466.0,20321383.0,20903278.0
20,Bangladesh,BGD,"Population, total",SP.POP.TOTL,48013505,49362834,50752150,52202008,53741721,55385114,...,149273134,151005733.0,152761413.0,154517385.0,156256287.0,157977151.0,159685421.0,161376713.0,163046173.0,164689383.0
21,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7867374,7943118,8012946,8078145,8144340,8204168,...,7348328,7305888.0,7265115.0,7223938.0,7177991.0,7127822.0,7075947.0,7025037.0,6975761.0,6927288.0
22,Bahrain,BHR,"Population, total",SP.POP.TOTL,162429,167899,173140,178142,182888,187432,...,1278153,1299942.0,1315029.0,1336073.0,1371853.0,1425793.0,1494077.0,1569440.0,1641164.0,1701583.0
23,"Bahamas, The",BHS,"Population, total",SP.POP.TOTL,109532,115119,121092,127340,133705,140060,...,359583,363581.0,367162.0,370625.0,374200.0,377923.0,381749.0,385635.0,389486.0,393248.0
24,Bosnia and Herzegovina,BIH,"Population, total",SP.POP.TOTL,3225664,3288604,3353228,3417573,3478999,3535632,...,3661173,3604972.0,3542598.0,3482106.0,3429362.0,3386263.0,3351534.0,3323929.0,3300998.0,3280815.0
25,Belarus,BLR,"Population, total",SP.POP.TOTL,8198000,8271216,8351928,8437232,8524224,8610000,...,9473172,9464495.0,9465997.0,9474511.0,9489616.0,9501534.0,9498264.0,9483499.0,9417849.0,9398861.0
26,Belize,BLZ,"Population, total",SP.POP.TOTL,92068,94700,97392,100165,103069,106120,...,330236,338001.0,345707.0,353366.0,360926.0,368399.0,375775.0,383071.0,390351.0,397621.0
27,Bermuda,BMU,"Population, total",SP.POP.TOTL,44400,45500,46600,47700,48900,50100,...,64564,64798.0,65001.0,65138.0,65237.0,64554.0,63873.0,63919.0,63913.0,63903.0
28,Bolivia,BOL,"Population, total",SP.POP.TOTL,3656961,3728954,3802996,3879191,3957759,4038865,...,10212951,10377677.0,10542375.0,10706517.0,10869732.0,11031822.0,11192853.0,11353140.0,11513102.0,11673029.0
29,Brazil,BRA,"Population, total",SP.POP.TOTL,72179235,74311338,76514329,78772647,81064572,83373533,...,197514541,199287292.0,201035904.0,202763744.0,204471759.0,206163056.0,207833825.0,209469320.0,211049519.0,212559409.0
30,Barbados,BRB,"Population, total",SP.POP.TOTL,230985,231718,232623,233632,234588,235415,...,282987,283698.0,284294.0,284825.0,285327.0,285798.0,286229.0,286640.0,287021.0,287371.0
31,Brunei Darussalam,BRN,"Population, total",SP.POP.TOTL,81707,85560,89484,93540,97819,102390,...,393687,398997.0,404414.0,409778.0,414914.0,419791.0,424481.0,428960.0,433296.0,437483.0
32,Bhutan,BTN,"Population, total",SP.POP.TOTL,223284,228849,234552,240529,246961,253993,...,693297,701582.0,710235.0,719053.0,727885.0,736706.0,745563.0,754396.0,763094.0,771612.0
33,Botswana,BWA,"Population, total",SP.POP.TOTL,502733,512688,523777,535692,547870,559996,...,2015406,2039551.0,2062551.0,2088619.0,2120716.0,2159925.0,2205076.0,2254067.0,2303703.0,2351625.0
34,Central African Republic,CAF,"Population, total",SP.POP.TOTL,1501668,1526057,1551908,1579375,1608618,1639706,...,4418639,4436411.0,4447945.0,4464171.0,4493171.0,4537683.0,4596023.0,4666375.0,4745179.0,4829764.0
35,Canada,CAN,"Population, total",SP.POP.TOTL,17909009,18271000,18614000,18964000,19325000,19678000,...,34339328,34714222.0,35082954.0,35437435.0,35702908.0,36109487.0,36545295.0,37065178.0,37593384.0,38005238.0
36,Central Europe and the Baltics,CEB,"Population, total",SP.POP.TOTL,91401764,92232738,93009498,93840016,94715795,95440988,...,104174038,103935318.0,103713726.0,103496179.0,103257886.0,102994278.0,102740078.0,102538451.0,102398537.0,102246330.0
37,Switzerland,CHE,"Population, total",SP.POP.TOTL,5327827,5434294,5573815,5694247,5789228,5856472,...,7912398,7996861.0,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8575280.0,8636896.0
38,Channel Islands,CHI,"Population, total",SP.POP.TOTL,109419,110398,111464,112591,113777,114989,...,160990,162051.0,163039.0,164107.0,165387.0,166922.0,168666.0,170496.0,172264.0,173859.0
39,Chile,CHL,"Population, total",SP.POP.TOTL,8132988,8303804,8476895,8650390,8821855,8989607,...,17233584,17400359.0,17571511.0,17758969.0,17969356.0,18209072.0,18470435.0,18729166.0,18952035.0,19116209.0

In [28]:
regional_df = regional_df.rename(columns={"Three_Letter_Country_Code": "Country Code"})

In [33]:
regional_df

,Continent_Name,Continent_Code,Country_Name,Two_Letter_Country_Code,Country Code,Country_Number
0,Asia,AS,"Afghanistan, Islamic Republic of",AF,AFG,4.0
1,Europe,EU,"Albania, Republic of",AL,ALB,8.0
2,Antarctica,AN,Antarctica (the territory South of 60 deg S),AQ,ATA,10.0
3,Africa,AF,"Algeria, People's Democratic Republic of",DZ,DZA,12.0
4,Oceania,OC,American Samoa,AS,ASM,16.0
...,...,...,...,...,...,...
257,Africa,AF,"Zambia, Republic of",ZM,ZMB,894.0
258,Oceania,OC,Disputed Territory,XX,NaN,NaN
259,Asia,AS,Iraq-Saudi Arabia Neutral Zone,XE,NaN,NaN
260,Asia,AS,United Nations Neutral Zone,XD,NaN,NaN
261,Asia,AS,Spratly Islands,XS,NaN,NaN

In [7]:
pop_df = pop_df.rename(columns={"Country Name": "Country"})

In [30]:
regional_df["Country Code"]

0      AFG
1      ALB
2      ATA
3      DZA
4      ASM
      ...
257    ZMB
258    NaN
259    NaN
260    NaN
261    NaN
Name: Country Code, Length: 262, dtype: object

In [9]:
merged_df = pd.merge(esg_df, pop_df, on="Country")

In [10]:
merged_df

,Country,EPI 2000,EPI 2002,EPI 2004,EPI 2006,EPI 2008,EPI 2010,EPI 2012,EPI 2014,EPI 2016,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Albania,58.98,61.43,64.54,66.62,67.46,71.42,65.85,54.73,74.38,...,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,2837743.0
1,Algeria,46.81,47.51,48.17,48.93,49.79,67.41,48.56,50.08,70.28,...,36661438.0,37383899.0,38140135.0,38923688.0,39728020.0,40551398.0,41389174.0,42228415.0,43053054.0,43851043.0
2,Angola,42.79,43.72,45.15,47.51,48.47,36.35,47.57,28.69,51.32,...,24220660.0,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0
3,Argentina,51.73,53.01,53.12,55.20,56.07,61.05,56.48,49.55,79.84,...,41261490.0,41733271.0,42202935.0,42669500.0,43131966.0,43590368.0,44044811.0,44494502.0,44938712.0,45376763.0
4,Armenia,44.61,46.23,46.64,46.65,46.46,60.44,47.48,61.67,81.60,...,2876536.0,2884239.0,2897593.0,2912403.0,2925559.0,2936147.0,2944789.0,2951741.0,2957728.0,2963234.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Uruguay,56.27,59.40,57.67,57.00,56.80,59.11,57.06,53.61,73.98,...,3368926.0,3378975.0,3389436.0,3400439.0,3412013.0,3424139.0,3436645.0,3449290.0,3461731.0,3473727.0
113,Uzbekistan,29.12,29.39,30.53,31.40,32.17,42.27,32.24,43.23,63.67,...,29339400.0,29774500.0,30243200.0,30757700.0,31298900.0,31847900.0,32388600.0,32956100.0,33580350.0,34232050.0
114,Vietnam,48.39,49.85,48.88,49.87,50.63,59.00,50.64,38.17,58.50,...,88871384.0,89801926.0,90752593.0,91713850.0,92677082.0,93640435.0,94600643.0,95545959.0,96462108.0,97338583.0
115,Zambia,53.57,53.30,54.14,53.90,55.24,47.00,55.56,41.72,66.06,...,14023199.0,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0
116,Zimbabwe,49.47,49.71,50.38,50.54,51.80,47.82,52.76,49.54,59.25,...,12894323.0,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0

In [34]:
final_merged_df = merged_df.merge(regional_df, on='Country Code', how = 'left')

In [35]:
final_merged_df

,Country,EPI 2000,EPI 2002,EPI 2004,EPI 2006,EPI 2008,EPI 2010,EPI 2012,EPI 2014,EPI 2016,...,2016,2017,2018,2019,2020,Continent_Name,Continent_Code,Country_Name,Two_Letter_Country_Code,Country_Number
0,Albania,58.98,61.43,64.54,66.62,67.46,71.42,65.85,54.73,74.38,...,2876101.0,2873457.0,2866376.0,2854191.0,2837743.0,Europe,EU,"Albania, Republic of",AL,8.0
1,Algeria,46.81,47.51,48.17,48.93,49.79,67.41,48.56,50.08,70.28,...,40551398.0,41389174.0,42228415.0,43053054.0,43851043.0,Africa,AF,"Algeria, People's Democratic Republic of",DZ,12.0
2,Angola,42.79,43.72,45.15,47.51,48.47,36.35,47.57,28.69,51.32,...,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,Africa,AF,"Angola, Republic of",AO,24.0
3,Argentina,51.73,53.01,53.12,55.20,56.07,61.05,56.48,49.55,79.84,...,43590368.0,44044811.0,44494502.0,44938712.0,45376763.0,South America,SA,"Argentina, Argentine Republic",AR,32.0
4,Armenia,44.61,46.23,46.64,46.65,46.46,60.44,47.48,61.67,81.60,...,2936147.0,2944789.0,2951741.0,2957728.0,2963234.0,Europe,EU,"Armenia, Republic of",AM,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Uruguay,56.27,59.40,57.67,57.00,56.80,59.11,57.06,53.61,73.98,...,3424139.0,3436645.0,3449290.0,3461731.0,3473727.0,South America,SA,"Uruguay, Eastern Republic of",UY,858.0
119,Uzbekistan,29.12,29.39,30.53,31.40,32.17,42.27,32.24,43.23,63.67,...,31847900.0,32388600.0,32956100.0,33580350.0,34232050.0,Asia,AS,"Uzbekistan, Republic of",UZ,860.0
120,Vietnam,48.39,49.85,48.88,49.87,50.63,59.00,50.64,38.17,58.50,...,93640435.0,94600643.0,95545959.0,96462108.0,97338583.0,Asia,AS,"Vietnam, Socialist Republic of",VN,704.0
121,Zambia,53.57,53.30,54.14,53.90,55.24,47.00,55.56,41.72,66.06,...,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,Africa,AF,"Zambia, Republic of",ZM,894.0
122,Zimbabwe,49.47,49.71,50.38,50.54,51.80,47.82,52.76,49.54,59.25,...,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,Africa,AF,"Zimbabwe, Republic of",ZW,716.0

In [14]:
merged_df.to_csv("merged_csv.csv",index=False)

In [38]:
final_merged_df.to_csv("final_merged_csv.csv",index=False)