In [1]:
# Dependencies
import pandas as pd
import pymongo

In [2]:
International_ESG_df = pd.read_csv('final_merged_csv.csv')

In [3]:
International_ESG_df.head()

,Country,EPI 2000,EPI 2002,EPI 2004,EPI 2006,EPI 2008,EPI 2010,EPI 2012,EPI 2014,EPI 2016,...,2016,2017,2018,2019,2020,Continent_Name,Continent_Code,Country_Name,Two_Letter_Country_Code,Country_Number
0,Albania,58.98,61.43,64.54,66.62,67.46,71.42,65.85,54.73,74.38,...,2876101.0,2873457.0,2866376.0,2854191.0,2837743.0,Europe,EU,"Albania, Republic of",AL,8
1,Algeria,46.81,47.51,48.17,48.93,49.79,67.41,48.56,50.08,70.28,...,40551398.0,41389174.0,42228415.0,43053054.0,43851043.0,Africa,AF,"Algeria, People's Democratic Republic of",DZ,12
2,Angola,42.79,43.72,45.15,47.51,48.47,36.35,47.57,28.69,51.32,...,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,Africa,AF,"Angola, Republic of",AO,24
3,Argentina,51.73,53.01,53.12,55.20,56.07,61.05,56.48,49.55,79.84,...,43590368.0,44044811.0,44494502.0,44938712.0,45376763.0,South America,SA,"Argentina, Argentine Republic",AR,32
4,Armenia,44.61,46.23,46.64,46.65,46.46,60.44,47.48,61.67,81.60,...,2936147.0,2944789.0,2951741.0,2957728.0,2963234.0,Europe,EU,"Armenia, Republic of",AM,51

In [4]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb+srv://admin:admin@cluster0.5lstl.mongodb.net/myFirstDatabase?authSource=admin&replicaSet=atlas-efjkbc-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true'
client = pymongo.MongoClient(conn)

In [5]:
# Define database and collection
ESGdb = client.International_ESG_df
ESGdb.ESG.drop()

NameError: name 'db' is not defined

In [ ]:
#Load df into a MongoDB collection
collection = ESGdb.ESG
# Insert collection
#collection.insert_many

In [ ]:
#for index, row in df.iterrows():
    #print(row['Country'], row['c2'])

In [ ]:
collection.insert_many(International_ESG_df.to_dict('records'))